apiVersion: v1
kind: Service
metadata:
  name: redis
spec:
  type: NodePort   # <-- Insecure: exposes to entire node public IP
  selector:
    app: redis
  ports:
    - port: 6379
      targetPort: 6379
      nodePort: 30079
      protocol: TCP